### ISSUE TITLE
Bubbles won't load after waking pc

### ISSUE THREAD

**Issue by Hedronmx** [aprilis/messenger#11]
Bubbles don't work after I wake my pc from sleep, I get notifications and on the main app the latest messages are present but if I click the bubble it loads for ever.

**Comment by aprilis** [comment]
I've encountered this bug too, I'll try to fix it soon. By the way:
1. Make sure you have the latest version
2. Does it still load forever when you close the bubble and reopen it?
3. Does choosing "Reload page" from bubble menu (right-click on the icon on Plank) solve this problem?

**Comment by aprilis** [comment]
I've uploaded something that may fix this problem

**Comment by Geop0p3** [comment]
I haven't been able to test this. i'll let you know if the update worked!

**Comment by Hedronmx** [comment]
OK so, It's still happening after the update, I tried reload page and didn't help either.
