### ISSUE TITLE
Bubble closes when changing keyboard layouts

### ISSUE THREAD

**Issue by Vuneu** [aprilis/messenger#14]
Would it be possible to change that behavior?

**Comment by aprilis** [comment]
OK, I've changed the bubble behavior a little bit. Now it doesn't close on focus out event. We will see if it causes other problems or not

**Comment by Vuneu** [comment]
Thank you!

This kind of messes up the window switching functionality. You can avoid this by clicking outside of the conversation but it still feels a bit weird. Is there a way to close the conversation when you switch active windows?
