### ISSUE TITLE
Granite.Widgets.AppMenu has been deprecated since 0.4.1. Use Gtk.MenuButton

### ISSUE THREAD

**Issue by Philip-Scott** [aprilis/messenger#15]
AppMenu is now deprecated, and causes the app to fail to compile now. You can use Gtk.MenuButton now though :)

```
/messenger/src/HeaderBar.vala:24.13-24.32: error: The name `icon_widget' does not exist in the context of `Granite.Widgets.AppMenu'
            app_menu.icon_widget = image;
```

**Comment by aprilis** [comment]
Ok, I've switched to Gtk.MenuButton but I can't say it was a pleasure :/

**Comment by Philip-Scott** [comment]
Yeah :/ Gtk's is a bit uglier, but it's more consistent with the rest of the apps. The one from granite was created before Gtk had one
