### ISSUE TITLE
Undefined symbol: plank_dbus_client_get_menu_position

### ISSUE THREAD

**Issue by LaVieEstDure** [aprilis/messenger#16]
Messenger launches normally and the GTK window shows up fine. Pressing on one of the chats opens a chat bubble but when it tries to open a chat window, messenger crashes. Relaunching messenger from terminal and trying again, the message `messenger: symbol lookup error: messenger: undefined symbol: plank_dbus_client_get_menu_position` is shown just before it crashes at the same point. 

Here's the log from terminal. I have replaced some part of the URLs with XXXXX because I wasnt sure if it included sensitive information (probably did)
```
set screen loading
attempt to connect

(messenger:8422): GLib-GObject-WARNING **: cannot register existing type 'DConfSettingsBackend'

(messenger:8422): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(messenger:8422): GLib-GIO-WARNING **: Tried to register an extension of the type (null) to extension point gsettings-backend. Expected type is GObject.
mqtt opening

(process:8430): GLib-GObject-WARNING **: cannot register existing type 'DConfSettingsBackend'

(process:8430): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(process:8430): GLib-GIO-WARNING **: Tried to register an extension of the type (null) to extension point gsettings-backend. Expected type is GObject.
load changed: WEBKIT_LOAD_STARTED
load changed: WEBKIT_LOAD_COMMITTED
load changed: WEBKIT_LOAD_FINISHED
set screen threads
CONSOLE ERROR Origin https://www.messenger.com is not allowed by Access-Control-Allow-Origin.
CONSOLE ERROR XMLHttpRequest cannot load https://6-edge-chat.facebook.com/sub?XXXXXX due to access control checks.
CONSOLE ERROR Origin https://www.messenger.com is not allowed by Access-Control-Allow-Origin.
CONSOLE ERROR XMLHttpRequest cannot load https://6-edge-chat.facebook.com/sub?XXXXXX due to access control checks.
connected!
ready
messenger: symbol lookup error: messenger: undefined symbol: plank_dbus_client_get_menu_position
```

**Comment by aprilis** [comment]
Make sure you have installed modified Plank version properly (it's step 2 from Getting Started section)

**Comment by LaVieEstDure** [comment]
Should have mentioned, it's been working for months before this happened and I already tried pulling again and building from /plank. Still doesnt work

**Comment by aprilis** [comment]
hmm, could you type in terminal 'plank --version' (without quotes) and show me the output?

**Comment by LaVieEstDure** [comment]
Matches the version in the custom build
```
/Messenger/messenger/build$ plank --version
0.11.3
```

**Comment by LaVieEstDure** [comment]
I think I found the problem. Tried building again and theres a libtool version mismatch.
```
Compilation succeeded - 7 warning(s)
  GEN      plank-resources.c
make  all-am
make[3]: Entering directory '/home/raghav/Desktop/Development/Messenger/messenger/plank/lib'
  CC       plank-resources.lo
libtool: Version mismatch error.  This is libtool 2.4.2, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2
libtool: and run autoconf again.
Makefile:1155: recipe for target 'plank-resources.lo' failed
make[3]: *** [plank-resources.lo] Error 63
make[3]: Leaving directory '/home/raghav/Desktop/Development/Messenger/messenger/plank/lib'
Makefile:826: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/raghav/Desktop/Development/Messenger/messenger/plank/lib'
Makefile:516: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/raghav/Desktop/Development/Messenger/messenger/plank'
Makefile:447: recipe for target 'all' failed
make: *** [all] Error 2
``` 

After researching some more, I found that its because Anaconda Python changed the PATH to `~/anaconda3/bin/libtool` and had version 2.4.2 while my actual libtool install was in `/usr/bin/libtool` with version 2.4.6. Not sure how to fix now :/

**Comment by LaVieEstDure** [comment]
Commented out the Anaconda path in `~/.bashrc` and it built perfectly fine afterwards. Installed again. `Undefined symbol: plank_dbus_client_get_menu_position ` issue remains

**Comment by aprilis** [comment]
That's not good... Just to make sure: did you run `sudo ldconfig` after installing Plank?

**Comment by LaVieEstDure** [comment]
Yeah, I did. Still havent figured out how to fix it

**Comment by aprilis** [comment]
So I've finally solved the problem (because it recently affected me too). Sorry that you had to wait so long (I hope you've found some kind of workaround by now)

**Comment by LaVieEstDure** [comment]
My work around was "not caring and using my web browser". Worked pretty well. 

Thanks for the fix!
