### ISSUE TITLE
Error  on building latest version 

### ISSUE THREAD

**Issue by CristianSarac** [aprilis/messenger#17]
I have pulled the latest changes but when i run `sudo make install` i get like 137 warnings and one error 
`/messenger/src/GroupCreator.vala:75.34-75.41: error: Argument 1: Cannot pass ref argument to non-reference parameter
                    list.remove (ref iter);
`
So the compilation fails

**Comment by aprilis** [comment]
Grrr, it seems that it depends on Gtk version (or its VAPI version). With the latest one you can't compile without the keyword `ref` with older ones you can't compile with it. Make sure your system is up-to-date. If it doesn't help, I've created a new branch that should compile with older VAPI version. `git pull` once again and then type `git checkout no_ref_iter`. After that you should be able to compile

**Comment by CristianSarac** [comment]
System is up-to-date. I have checkout the no_ref_iter branch and now it compiles

**Comment by CristianSarac** [comment]
So lately i have been having issues with login in , always had to click the reconnect button and then  the list would load but when i click on a conversation a web-view appears asking me to log in again , after that everything works ok. I saw you added some fixes to the master branch, will those also be merged in to the no_ref_iter branch ?

**Comment by aprilis** [comment]
I've added conditional compiling to the master branch so that now it should compile with both old and new vala version. Let me know if you still have any problems compiling it and, in that case, provide your vala version (via ```valac --version```)

**Comment by CristianSarac** [comment]
I just build the master branch and everything works Ok. 
Thanks, love the app
