### ISSUE TITLE
Is this normal ?

### ISSUE THREAD

**Issue by CristianSarac** [aprilis/messenger#18]
After i pulled the latest changes i noticed that Messenger is running very slow and also the usage of the CPU increased a lot 
![cpu](https://user-images.githubusercontent.com/3420861/33837180-d99db606-de8b-11e7-9e23-22a63ea4ba2d.png)

**Comment by aprilis** [comment]
No this isn't normal at all ;) Do you know which version you had before (or when was your previous update)?

**Comment by CristianSarac** [comment]
Before this [commit](https://github.com/aprilis/messenger/commit/b760744adbefc9a7a949e290187d303e45f1d594) everything was working fine

**Comment by aprilis** [comment]
Can you check if the last commit has helped anything?

**Comment by CristianSarac** [comment]
I have pulled the latest changes and the High CPU usage is gone , everything is OK now
