### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Vuneu** [aprilis/messenger#19]
I've been using the app on another computer, but after trying to build it on another one, I keep getting this error

```
CMakeFiles/messenger.dir/src/App.c.o: In function `__lambda79_':
App.c:(.text+0x8448): undefined reference to `plank_dbus_client_get_menu_position'
collect2: error: ld returned 1 exit status
CMakeFiles/messenger.dir/build.make:974: recipe for target 'messenger' failed
make[2]: *** [messenger] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/messenger.dir/all' failed
make[1]: *** [CMakeFiles/messenger.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

I built the modified version of Plank without issues, so I'm not sure what's up. [Here's](https://gist.github.com/Vuneu/baa3a1b82a8878c9ba2a6a0918faba86) the full output.

**Comment by aprilis** [comment]
I've encountered this bug too, so I hope I'll find the reason of the problem as soon as I have some free time for this (after Christmas probably).

**Comment by aprilis** [comment]
The latest commit should solve the problem
