### ISSUE TITLE
Doesn't open; unable to find cache dir

### ISSUE THREAD

**Issue by varun-magesh** [aprilis/messenger#2]
When running a clean install of messenger:
```
** (messenger:17038): WARNING **: App.vala:149: Error 1: Error opening file: No such file or directory
** (messenger:17038): WARNING **: App.vala:133: Error 4: Failed to open file '/home/USER/.cache/messenger/session': No such file or directory
```
I haven't looked at it for very long but it looks like it doesn't initialize a cache file if one doesn't already exist.

P.S: Looks like an awesome application, thanks for your work!

**Comment by aprilis** [comment]
Although it shows a warning with an error, it is expected behavior that the app can't open session file if you're not logged in. 
If you run the app from command line it starts in the background by default - you have to add "--activate" flag to show a window.

**Comment by varun-magesh** [comment]
Thanks for letting me know, sorry about that, should have read the README better. I saw an error and no window and assumed; whoopsie.
