### ISSUE TITLE
Plank overlays window when chat bubble is open.

### ISSUE THREAD

**Issue by NellyWhads** [aprilis/messenger#20]
When interacting with chat bubbles, a "maximized" window moves behind the plank, instead of sitting above it. One the interaction is complete (ie. the bubble is closed/minimized), the window automatically returns to it's original, above plank position. This occurs both when the main messenger window is open, and when it is closed.

Screenshots attached to better explain the issue - if there's anything I can do to help diagnose the issue please let me know!

PS. the screenshots are of a generic messenger bot to avoid privacy issues with my friends. This occurs on all conversations.

Pre-Interaction:
![pre-interaction](https://user-images.githubusercontent.com/8030181/34448545-49f63f20-eca3-11e7-9380-5ed6c3986424.png)

During-Interaction:
![during-interaction](https://user-images.githubusercontent.com/8030181/34448553-51372434-eca3-11e7-8ab7-d71c2c09f3ec.png)

Post-Interaction:
![post-interaction](https://user-images.githubusercontent.com/8030181/34448544-49e0ba38-eca3-11e7-9b91-9fd1b4f9472d.png)

Plank-Appearance:
![plank-appearance](https://user-images.githubusercontent.com/8030181/34448722-e7de2bca-eca4-11e7-9648-dcf602a5fda4.png)

Plank-Behaviour:
![plank-behaviour](https://user-images.githubusercontent.com/8030181/34448715-d621d5ee-eca4-11e7-952d-721f175451fa.png)

Plank-Version:
![plank-version](https://user-images.githubusercontent.com/8030181/34448760-74f7fd6a-eca5-11e7-96c6-a6ad6db34f1b.png)

Git-Log (this repo):
![git-log](https://user-images.githubusercontent.com/8030181/34448765-869ee290-eca5-11e7-83db-dd9b57f3e927.png)

**Comment by aprilis** [comment]
Fixed! Thanks for the bug report :)
