### ISSUE TITLE
can't stay logged in

### ISSUE THREAD

**Issue by benavern** [aprilis/messenger#21]
Hello. 
This project is very insteresting to me, I installed it, when I log in and click on someone, a window opens and asks me to login again and again ..........

Is this a known bug ? can you fix it ? 
I don't know how I can give you some logs or more explaination ...

Thank you in advance

**Comment by benavern** [comment]
Ok, after rebooting multiple times, It worked somehow ... :)

**Comment by aprilis** [comment]
It's good to hear you got it working somehow :) Do you use 2-factor authentication?

**Comment by benavern** [comment]
No I didn't. :)

**Comment by aprilis** [comment]
To anyone affected by this bug: it should be fixed now. After updating the app you can log out, open the app again and log in and everything should work
