### ISSUE TITLE
messenger window in a bubble

### ISSUE THREAD

**Issue by benavern** [aprilis/messenger#22]
Hi,
I like your app and wish it could reach the app-center one day but understood it can't because of the modified version of plank...

However, I was wondering if the messenger window could be presented as a bubble too ? 

Thanks in advance.

**Comment by aprilis** [comment]
Yes, it is possible to place any widget inside the bubble. When I have some time, I can make a bubble with all conversations list, but currently there are issues with higher priority. BTW sorry about this confusing message "aprilis added a commit that referenced this issue...". It was meant to refer to the previous issue you had reported

**Comment by benavern** [comment]
Hi! I come back again 'cause I still use your app and still would like to see this feature comming ;)

**Comment by aprilis** [comment]
Hi! Good to hear you're using my app :) I'm just back from holidays and hopefully I'll find some time to implement this feature soon

**Comment by benavern** [comment]
Cool! Let me know if I can help somehow (again, I am a web developer, not comfortable with vala and stuff ... but could learn if it remains simple )

**Comment by aprilis** [comment]
I've implemented this feature in the latest commit. You can activate it via preferences (after that you have to quit the app and run again). And be prepared for bugs of course :)
BTW thanks for your help offer, but I think the code is too messy now, it needs solid refactoring before someone else can start working with it.

**Comment by benavern** [comment]
Great!!!
I just tried & adopted it! It is much more natural to me!

Thank you!

I think there are other things to make it suit better for my needs:
- an icon that reminds more of facebook messenger
- the main window with a better support for the native dark theme of elementary

![capture d ecran du 2018-09-06 20 16 58](https://user-images.githubusercontent.com/5999900/45177008-005c3b00-b212-11e8-893d-771264fe0f2f.jpeg)

Thank you again anyway!

**Comment by aprilis** [comment]
Yeah, this app definietely needs an icon, currently it's just using one of the system icons. That's a thing where some help would be appreciated :) And thanks for the info about dark theme issues

**Comment by alizehctl** [comment]
Why not just use the Facebook Messenger icon from one of the elementary icon packs?

**Comment by benavern** [comment]
This one could do the job pretty well (rounded & facebook flaored, it's also free & with no link back need):
https://www.iconfinder.com/icons/3225189/app_logo_media_messenger_popular_social_icon

**Comment by alizehctl** [comment]
@benavern this would be even better since it is designed for elementary and is very close to the original messenger icon

https://github.com/mank319/elementaryPlus/blob/master/elementaryPlus/apps/128/messengerfordesktop.svg

**Comment by benavern** [comment]
@aadilayub Yes you are right it is designed for elementary, I did just look for a completely round icon to keep the same design as the avatar icons that the app puts in plank.

@aprilis the choice is yours XD

**Comment by aprilis** [comment]
I like the one from elementaryPlus set. I think it would be nice to have an icon designed only for this app but I'll consider that one too

**Comment by aprilis** [comment]
Now the app looks great with dark theme too so I guess I can close the issue
