### ISSUE TITLE
Could not display composer

### ISSUE THREAD

**Issue by Hedronmx** [aprilis/messenger#24]
I've been having this problem lately, where I open a conversation and an error would pop in the composer saying "Could not display composer". After that I can't type any messages in any of my conversations. I would have to restart the app to finally type again.

It seems to run at random. Running latest version from 9 days ago(Main window in bubble version).
![Imgur](https://i.imgur.com/wjWmlOV.jpg)

**Comment by aprilis** [comment]
You can see in Google that it's quite common bug in Facebook Messenger. I haven't figured out what's the reason of the problem yet, but I've written a workaround that should reload page whenever this message appears. By the way, if something goes wrong, you can always right-click on any chat icon and use the "Reload page" option

**Comment by Hedronmx** [comment]
Thank you! I was getting more and more frustrated. Now Ill keep using this app.
Edit- Just tested, it works great! Thank you
