### ISSUE TITLE
ULauncher quick conversation search

### ISSUE THREAD

**Issue by Hedronmx** [aprilis/messenger#25]
I have two machines running eOS, in my pc I can use ulauncher to launche a conversation and this would open directly a bubble. Now, on my laptop I can't search this. I'm not sure if you changed something in the app, or if ulauncher changed this but it was a really good feature.

Any ideas where I could find those shortcuts, if they even exist?
Sorry if this is not the place to post this.

**Comment by aprilis** [comment]
Actually I have no idea why ulauncher found launchers for the conversations before. I can only say that I haven't changed anything related to the launchers. The perfect solution would be to write an extension for ulauncher but I don't think I'll have time for this soon

**Comment by Hedronmx** [comment]
That's weird, I also have no idea why that happened but it was a nice feature to have. I will take a look at the extensions, maybe I could make one.
