### ISSUE TITLE
Juno animation error

### ISSUE THREAD

**Issue by Hedronmx** [aprilis/messenger#26]
I have installed this on juno and now animations are not working correctly on plank. When I click to open an app, the animation plays only at the start of the system, after a while animation gets faster and faster, until you can't see it anymore. If you killall plank then it resets to playing the animation for a while.

How can I restore plank so I can try and see if this app is the problem.

Thanks.

**Comment by aprilis** [comment]
You should be able to uninstall modified Plank version by entering `messenger/plank` directory and typing `sudo make uninstall`

**Comment by Hedronmx** [comment]
Alright so I uninstalled your modified version of plank and now the animation is back to normal. Any ideas on why??

**Comment by aprilis** [comment]
I guess Plank has received some updates in Juno but I'll have to check it

**Comment by Hedronmx** [comment]
Please do :D

**Comment by aprilis** [comment]
Hmm I've installed Juno and I can't see any issues with Plank behavior. But the good news is that Juno has the up-to-date version of Plank with some patches from me so it's possible now to integrate the app with the official version installed by default

**Comment by Hedronmx** [comment]
So should I reinstall plank and just build messenger, ignoring the plank steps? What should I do?
It's weird because I have two machines with the same problem, no bounce animation when clicking on an app.

**Comment by Hedronmx** [comment]
I have reinstalled Juno and the animation error happens when I use your modified plank.

**Comment by aprilis** [comment]
I need to make some changes in code to make the app work with default Plank version but hopefully I'll finish it today

**Comment by aprilis** [comment]
OK, I've pushed changed to the new_api_plank brach. You can download it by typing
```
git checkout new_api_plank
git pull
```
Then build and install as always. If you have forked Plank version, you can run `script/uninstall-plank.sh` to remove it. Please let me know if everything works fine

**Comment by Hedronmx** [comment]
Cant pull on new_api_plank
error-
Please commit your changes or stash them before you merge.

**Comment by aprilis** [comment]
type `git reset --hard` and try again

**Comment by Hedronmx** [comment]
There's no autogen file in that branch.... I can't follow the read me instructions.
Sorry for this, I'm not that advanced

**Comment by aprilis** [comment]
You don't need the autogen file anymore. Just skip the part about installing plank. You can see updated README here https://github.com/aprilis/messenger/tree/new_api_plank

**Comment by Hedronmx** [comment]
Works perfectly, feels snappier. Love it! Thank you
