### ISSUE TITLE
undefined reference to `plank_dbus_client_get_hover_position'

### ISSUE THREAD

**Issue by ghost** [aprilis/messenger#29]
I've previously installed Messenger and tried to update. Here are the steps I've taken:

1. Removed old version of Plank
2. Moved to build folder and ran `cmake ..` (not a required step, but did anyway)
3. Ran `make`

I've also tried this with a clean copy from git. Here's the recurring output:

```
CMakeFiles/messenger.dir/src/App.c.o: In function `__lambda80_':
App.c:(.text+0x8740): undefined reference to `plank_dbus_client_get_hover_position'
CMakeFiles/messenger.dir/src/MainWindowManager.c.o: In function `___lambda87_':
MainWindowManager.c:(.text+0xff5): undefined reference to `plank_dbus_client_get_hover_position'
collect2: error: ld returned 1 exit status
CMakeFiles/messenger.dir/build.make:1006: recipe for target 'messenger' failed
make[2]: *** [messenger] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/messenger.dir/all' failed
make[1]: *** [CMakeFiles/messenger.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by aprilis** [comment]
If you're using Loki (old elementary version), you need to clone another branch (more details [here](https://github.com/aprilis/messenger/blob/loki/README.md)). If you're using Juno, you need to uninstall old Plank version by typing `sudo script/uninstall-plank.sh` from the `messenger` folder

**Comment by ghost** [comment]
I may have forgotten to use sudo. Will check soon!

**Comment by ghost** [comment]
Woah, it turns out I am using a 0.4.1. I thought I had the latest install. Sorry for the inconvenience.
