### ISSUE TITLE
Login twice 

### ISSUE THREAD

**Issue by CristianSarac** [aprilis/messenger#30]
I dont know if this is related to the App behavior or Facebook changed something in their API , but after i enter the email and password i get a second window from Facebook telling me that i have to enter my credentials again because 

> Aplication password detected.Please log in with your real password here

Even if i have the checkbox ticked to keep me signed in , i always get this popup.
Is this behavior intended or Facebook changed something ?

**Comment by aprilis** [comment]
Something has changed in the facebook website. The latest commit should fix the problem

**Comment by CristianSarac** [comment]
I tried to build the latest changes but when i try to `sudo make install` i get the following message 

> -- checking for Vala version of 0.26
--   found Vala, version 0.40.11
-- Checking for one of the modules 'valacef'
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:645 (message):
  None of the required 'valacef' found
Call Stack (most recent call first):
  CMakeLists.txt:128 (pkg_search_module)
-- Checking for one of the modules 'valacefgtk'
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:645 (message):
  None of the required 'valacefgtk' found
Call Stack (most recent call first):
  CMakeLists.txt:132 (pkg_search_module)
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- GSettings schemas will be installed into /usr/local/share/glib-2.0/schemas/
-- Configuring incomplete, errors occurred!
Makefile:1154: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1

**Comment by aprilis** [comment]
Sorry, I've commited a wrong file, now it should work

**Comment by CristianSarac** [comment]
I have pulled the latest changes and now the problem is gone, no more login twice.
