### ISSUE TITLE
Can't build latest version

### ISSUE THREAD

**Issue by Hedronmx** [aprilis/messenger#31]
I get this error
`Checking for one of the modules 'valacef'
CMake Error at /usr/share/cmake-3.10/Modules/FindPkgConfig.cmake:645 (message):
  None of the required 'valacef' found
Call Stack (most recent call first):
  CMakeLists.txt:128 (pkg_search_module)
`

**Comment by aprilis** [comment]
Oops I commited a wrong file, should be fixed now

**Comment by aprilis** [comment]
Can you confirm the issue is solved?

**Comment by Hedronmx** [comment]
Yes, sorry! Forgot to close this.
