### ISSUE TITLE
Notifications doesn't work

### ISSUE THREAD

**Issue by siigdev** [aprilis/messenger#32]
At first, I have been using this a long time and in my opinion it is by far the best application for elementary, so thank you a lot.

However, recently the notifications does not show up .
It started with a notification message from Messenger. Then all message notifications appeared the same:

> "Thank you for using Messenger. We regret to inform you that starting today, March 29, the version of the app you're using will no longer be supported and will no longer allow you to send and receive messages. To continue using Messenger, please update your Messenger app to the latest version .... google play store link"

I can still send and receive messages, they just does not popup the way they used to. Is this something new or known? (even though it says March)

**Comment by aprilis** [comment]
This problem came up 3 days ago and is related to the facebook API library I'm using (https://github.com/dequis/purple-facebook/issues/449). Its author is working on the solution so I hope some updates will be released soon.

**Comment by aprilis** [comment]
OK, please update and check if everything works fine now

**Comment by siigdev** [comment]
Can confirm that it now works just fine here.
Thanks a lot.
