### ISSUE TITLE
Incoming call sound doesn't stop

### ISSUE THREAD

**Issue by siigdev** [aprilis/messenger#33]
Whenever a Facebook call is received, the ringing sound of the incoming call continues.
I don't mind not being able to answer the call, but it's a bit annoying that the sound does not stop until the application is fully closed.

The sound also keeps going even infinitely even though the call is being responded by another device.

Is there any quick fix for this? Thanks

**Comment by aprilis** [comment]
Sorry, I have no time for this now, you can expect some updates around next Wednesday

**Comment by siigdev** [comment]
It is alright. 
It was just if you knew something, but no problem

**Comment by aprilis** [comment]
Ok, sorry for delay. It seems to be a bug of WebKit (you can experience the same problem in Epiphany Web Browser). Can't wait to replace it with Blink (Chrome's engine) finally. As a workaround, I've disabled the incoming call sound completely, so when you update, you should no longer hear this annoying sound
