### ISSUE TITLE
Weird error not allowing start

### ISSUE THREAD

**Issue by artistro08** [aprilis/messenger#37]
```
(com.github.aprilis.messenger:9061): GLib-GIO-ERROR **: 07:59:31.524: Settings schema 'com.github.aprilis.messenger' is not installed
```

That's what i get when I run: 

```
com.github.aprilis.messenger --activate
```

Weird. thoughts?

**Comment by aprilis** [comment]
Try `sudo glib-compile-schemas /usr/share/glib-2.0/schemas/` and then start the app again

**Comment by artistro08** [comment]
That works!

**Comment by artistro08** [comment]
Now i get this error upon runnning 
![image](https://user-images.githubusercontent.com/6427230/59391022-a2c4c400-8d38-11e9-8c7d-1b37cd45d45f.png)
