### ISSUE TITLE
Improve Interface

### ISSUE THREAD

**Issue by NathanBnm** [aprilis/messenger#38]
Messenger has been updated. Maybe you can think about improving the interface to fit better with the new look. (I cannot do screenshots for now but I'll post some later).

For example the "friend selection list" is now always present in each bubble.

**Comment by aprilis** [comment]
Ok, it would be great if you could post some screenshots

**Comment by NathanBnm** [comment]
![Capture d'écran du 2019-06-20 17 22 18](https://user-images.githubusercontent.com/45366162/59861039-5f91d300-9380-11e9-90ba-47ad67a1eb78.png)

**Comment by NathanBnm** [comment]
Messenger just updated again. There were some changes on the text input section:

![Capture d'écran du 2019-06-22 17 06 37](https://user-images.githubusercontent.com/45366162/59965580-5c2d5180-9510-11e9-8980-5b1db7ad9d0c.png)

**Comment by aprilis** [comment]
My messenger still looks the same, so I'm not able to make proper modifications. You can open messenger website in a browser, right-click on the panel and select "Inspect element" or something similar and find the topmost element in the DOM tree which contains only the panel (for me it's <div class="_1enh">). When you find it, you can add a rule to STYLE_SHEET in Conversation.vala, similar to the one defined for "div._1enh".

**Comment by NathanBnm** [comment]
I'll check that. For now I'm fixing warnings (removing deprecation etc.)
EDIT: I'll do a PR

**Comment by Hedronmx** [comment]
I still get the user list UI from time to time even though I have updated messenger. If I close the app and reopen the user list disappears until it appears again some time randomly
