### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by getuslocal** [aprilis/messenger#47]
After doing the first part I went to start the build and this is what I receive

 meson build

ERROR: Neither directory contains a build file meson.build.

**Comment by aprilis** [comment]
You need to open directory called `messenger` in your terminal. You can change current directory to `xyz` by typing `cd xyz` or you can go up by typing `cd ..`. To list all directory contents type `ls -l`. Probably all you need to do is type `cd messenger`. Another option is to find this directory in file manager and select `Open in -> Terminal` in the right-click menu.

Once you are in the right place in your terminal, you can paste commands from the step 2.
