### ISSUE TITLE
Can't log in with two factor authentication turned on

### ISSUE THREAD

**Issue by michaljenicek** [aprilis/messenger#57]
Hi, I am using two-factor authentication on my Facebook account and can't log into the messenger app.

When I enter my usual Facebook password I get this message:

![Screenshot from 2020-11-07 16-06-12](https://user-images.githubusercontent.com/21178057/98444843-660b2100-2114-11eb-977b-ef34bf8ed8d9.png)

However, when I generate an app password in my Facebook account and enter it in the messenger app, I get this error message:

![Screenshot from 2020-11-07 16-04-58](https://user-images.githubusercontent.com/21178057/98444872-95219280-2114-11eb-93f4-7762839953fb.png)

and my Facebook account gets temporarily blocked:

![Screenshot from 2020-11-07 16-05-18](https://user-images.githubusercontent.com/21178057/98444883-a5d20880-2114-11eb-88ab-3b0e518fcda5.png)

How can I overcome this Issue?

Thank you.

**Comment by aprilis** [comment]
Please
1. Open you app by running in terminal `com.github.aprilis.messenger --activate`
2. Try to log in
3. Copy your terminal output and send it by email to me (kwiecienjaro@gmail.com)

**Comment by michaljenicek** [comment]
Hi, I managed to work it out, the issue was with my VPN provider and not with your app, thank you for your time and sorry for the bother.
