### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Philip-Scott** [aprilis/messenger#6]
Even after following your instructions on the readme, i haven't being able to make it compile :/ 

``` 
CMakeFiles/messenger.dir/src/App.c.o: In function `__lambda68_':
App.c:(.text+0x7c52): undefined reference to `plank_dbus_client_get_menu_position'
collect2: error: ld returned 1 exit status
CMakeFiles/messenger.dir/build.make:794: recipe for target 'messenger' failed
make[2]: *** [messenger] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/messenger.dir/all' failed
make[1]: *** [CMakeFiles/messenger.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by aprilis** [comment]
Seems that you don't have the modified version of Plank. Are you sure you have successfully compiled it and installed (step number 2 from Getting Started)?
EDIT: sorry, it's linker not compiler error. So you have at least headers for this Plank version. Maybe try typing "sudo ldconfig". You can also clean all files in messenger/build directory and try to generate makefile again (all instructions from step 3). Finally, if it doesn't help you can edit CMakeLists.txt in the main directory and replace "target_link_libraries(${EXEC_NAME} PUBLIC ${PLANK_LIBRARIES})" with a command linking proper libplank version

**Comment by Philip-Scott** [comment]
It might be a problem with using the Daily PPA. I was able to install it from a clean system!

Thanks :)
