### ISSUE TITLE
Latest version (0.2.2) can't compile

### ISSUE THREAD

**Issue by LordManhattan** [aprilis/messenger#9]
Been using the app for a while now, and I just pulled the latest version (0.2.2), but I'm getting this error message when I try to compile it:

```
~/messenger/build$ sudo make install
-- checking for Vala version of 0.26
--   found Vala, version 0.34.9
-- Checking for one of the modules 'libnotify'
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:578 (message):
  None of the required 'libnotify' found
Call Stack (most recent call first):
  CMakeLists.txt:107 (pkg_search_module)


-- Configuring incomplete, errors occurred!
See also "/home/steffen/messenger/build/CMakeFiles/CMakeOutput.log".
Makefile:942: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1

```

Libnotify (libnotify4) is installed, and everything has been working fine. The app itself still works fine, but it won't apparently install this update for some odd reason.

Here's the CMakeOutput.log: https://pastebin.com/HmZ4rs5c

Thoughts?

**Comment by aprilis** [comment]
Are you sure you have package libnotify-dev installed? libnotify4 contains only run-time files and it's not enough to compile software using it

**Comment by LordManhattan** [comment]
Solved! Libnotify-dev was not installed, and it's all working fine after installing it. Thanks!
